#!/usr/bin/env perl
#
# speedread:  A simple terminal-based open source spritz-alike
#
# Show input text as a per-word RSVP (rapid serial visual presentation)
# aligned on optimal reading points.  This kind of input mode allows
# reading text at a much more rapid pace than usual as the eye can
# stay fixed on a single place.
#
# (c) Petr Baudis <pasky@ucw.cz>  2014
# MIT licence
#
# Usage: cat file.txt | speedread [-w WORDSPERMINUTE] [-r RESUMEPOINT] [-m] [-f]
#
# Controls:
#   [     - slow down by 10%
#   ]     - speed up by 10%
#   space - pause (and show last two lines of context)
#   b     - seek back 10 words
#   B     - seek back 30 words
#   q     - quit with stats and resume point

use warnings;
use strict;
use autodie;
use v5.14;

my $wpm        = 250;
my $resume     = 0;
my $multiword  = 0;
my $fullscreen = 0;

# Timing coefficients (all relative to wpm unless noted)
my $wordtime  = 0.9;   # base time per word
my $lentime   = 0.04;  # * sqrt(length), added to base
my $commatime = 2;     # multiplier for comma/semicolon/colon endings
my $fstoptime = 3;     # multiplier for sentence-ending punctuation
my $multitime = 1.2;   # multiplier for joined multi-words
my $firsttime = 0.2;   # [s] minimum time for the very first word

my $ORPloc      = 0.35;
my $ORPvisualpos = 20;
my $cursorpos   = 64;

use utf8;
binmode(STDIN, ":encoding(UTF-8)");
binmode(STDOUT, ":encoding(UTF-8)");

use Term::ANSIColor;
use POSIX qw(floor);
use Time::HiRes qw(time sleep gettimeofday tv_interval);

use Getopt::Long;
GetOptions(
    "wpm|w=i"        => \$wpm,
    "resume|r=i"     => \$resume,
    "multiword|m"    => \$multiword,
    "fullscreen|f"   => \$fullscreen,
    "wordtime=f"     => \$wordtime,
    "lentime=f"      => \$lentime,
    "commatime=f"    => \$commatime,
    "fstoptime=f"    => \$fstoptime,
    "firsttime=f"    => \$firsttime,
);

my $paused          = 0;
my $current_word    = '';
my $current_orp     = 0;
my $next_word_time  = 0;
my $next_input_time = 0;

my ($term_rows, $term_cols) = (24, 80);
my $display_row = 1;

my @lastlines;
my $tty = rawinput->new();
$| = 1;

my $wordcounter   = 0;
my $lettercounter = 0;
my $t0 = [gettimeofday];

# Short but semantically heavy words that get missed at high wpm
my %emphasis_words = map { $_ => 1 } qw(
    not no nor never neither
    can may must will shall would could should
    but yet although though however
    and or for so if
);

sub get_term_size {
    if (open(my $fh, '-|', 'stty size 2>/dev/null')) {
        my $size = <$fh>;
        close($fh);
        return ($1, $2) if $size && $size =~ /^(\d+)\s+(\d+)/;
    }
    return (24, 80);
}

sub move_to {
    my ($row, $col) = @_;
    printf "\033[%d;%dH", $row, $col // 1;
}

sub setup_fullscreen {
    ($term_rows, $term_cols) = get_term_size();
    $display_row = int($term_rows / 2) - 1;
    $display_row = 2 if $display_row < 2;
    print "\033[2J";    # clear screen
    print "\033[?25l";  # hide cursor
}

sub teardown_fullscreen {
    print "\033[${term_rows};1H";
    print "\033[?25h";  # show cursor
    print "\n";
}

sub print_stats {
    my $elapsed = tv_interval($t0, [gettimeofday]);
    my $truewpm = $elapsed > 0 ? $wordcounter / $elapsed * 60 : 0;
    if ($fullscreen) {
        move_to($display_row + 3, 1);
    }
    printf("\n %.2fs, %d words, %d letters, %s%.2f%s true wpm\n",
        $elapsed, $wordcounter, $lettercounter,
        color('bold green'), $truewpm, color('reset'));
}

$SIG{INT} = sub {
    teardown_fullscreen() if $fullscreen;
    print_stats();
    my $resume_word = $wordcounter + $resume;
    say " To resume from this point run with argument -r $resume_word";
    exit;
};

main();

# ORP: Optical Recognition Point
sub find_ORP {
    my ($word) = @_;
    return 4 if length($word) > 13;
    return (0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3)[length($word)];
}

sub show_word {
    my ($word, $i) = @_;

    if ($fullscreen) {
        # Redraw guide + word in place every frame
        move_to($display_row, 1);
        print "\033[K" . " " x $ORPvisualpos . color('red') . "v" . color('reset');
        move_to($display_row + 1, 1);
    }

    my $pivotch = substr($word, $i, 1);
    $pivotch = "\x{00B7}" if $pivotch eq ' ';

    print("\r\033[K"
        . " " x ($ORPvisualpos - $i)
        . color("bold")
        . substr($word, 0, $i)
        . color("red")
        . $pivotch
        . color("reset")
        . color("bold")
        . substr($word, $i + 1)
        . color("reset")
        . " " x ($cursorpos - (($ORPvisualpos - $i) + length($word)))
        . "$wpm wpm"
        . ($paused ? "  " . color("yellow") . "PAUSED" . color("reset") : ""));
}

sub word_time {
    my ($word) = @_;

    my $time = $wordtime;
    if ($word =~ /[.?!]\W*$/) {
        $time = $fstoptime;
    } elsif ($word =~ /[:;,]\W*$/) {
        $time = $commatime;
    } elsif ($word =~ / /) {
        $time = $multitime;
    } elsif (length($word) <= 4 && exists $emphasis_words{lc($word =~ s/\W+//gr)}) {
        # Short but important words that get skipped over at high wpm
        $time = $wordtime * 1.4;
    }
    $time += sqrt(length($word)) * $lentime;
    $time *= 60 / $wpm;
    $time = $firsttime if $wordcounter == 0 && $time < $firsttime;
    return $time;
}

sub print_context {
    my ($wn) = @_;
    if ($fullscreen) {
        move_to($display_row - 3, 1);
        print "\033[K";
        say $lastlines[1] // '';
        print "\033[K";
    } else {
        print "\r\033[K\033[A\033[K";
        say $lastlines[1] if $lastlines[1];
    }
    my $line0 = $lastlines[0] // '';
    my $c0 = color('yellow');
    my $c1 = color('reset');
    $line0 =~ s/^((?:.*?(?:-|\s)+){$wn})(.*?)(-|\s)/$1$c0$2$c1$3/;
    say $line0;
}

sub process_keys {
    my ($word, $i, $wn) = @_;
    my $seek = 0;
    while ($tty->key_pressed()) {
        my $ch = $tty->getch();
        if ($ch eq '[') {
            $wpm = int($wpm * 0.9);
        } elsif ($ch eq ']') {
            $wpm = int($wpm * 1.1);
        } elsif ($ch eq 'b') {
            $seek -= 10;
        } elsif ($ch eq 'B') {
            $seek -= 30;
        } elsif ($ch eq 'q') {
            teardown_fullscreen() if $fullscreen;
            print_stats();
            my $resume_word = $wordcounter + $resume;
            say " To resume from this point run with argument -r $resume_word";
            exit;
        } elsif ($ch eq ' ') {
            $paused = not $paused;
            if ($paused) {
                print_context($wn);
                show_word($word, $i);
            } else {
                $next_word_time = time();
            }
        }
    }
    return $seek;
}

sub main {
    # Pre-load all words so we can seek backward
    my @allwords;
    my @word_meta;  # [$wn_in_line, \@linebuf_snapshot] per word
    my @linebuf;

    while (<>) {
        chomp;
        unshift @linebuf, $_;
        pop @linebuf if @linebuf > 2;

        my @words = grep { /./ } split /(?:-|\s)+/;

        if ($multiword) {
            for (my $i = 0; $i < $#words - 1; $i++) {
                if (length($words[$i]) <= 3 && length($words[$i + 1]) <= 3) {
                    $words[$i] .= ' ' . $words[$i + 1];
                    splice(@words, $i + 1, 1);
                }
            }
        }

        my $wn = 0;
        for my $w (@words) {
            $wn++;
            push @allwords, $w;
            push @word_meta, [$wn, [@linebuf]];
        }
    }

    setup_fullscreen() if $fullscreen;

    unless ($fullscreen) {
        # Non-fullscreen: print the guide once above the word line
        say(" " x $ORPvisualpos . color('red') . "v" . color('reset') . "\033[K");
    }

    $next_word_time  = time();
    $next_input_time = time();

    my $total = scalar @allwords;
    my $idx   = ($resume < $total) ? $resume : $total - 1;
    $idx = 0 if $idx < 0;

    my $wn = 0;

    while ($idx < $total) {
        my $current_time = time();

        if ($next_word_time <= $current_time && !$paused) {
            $current_word = $allwords[$idx];
            ($wn, my $lb)  = @{$word_meta[$idx]};
            @lastlines     = @$lb;
            $current_orp   = find_ORP($current_word);
            $next_word_time += word_time($current_word);
            $wordcounter++;
            $lettercounter += length($current_word);
            $idx++;
        }

        if ($next_input_time <= $current_time) {
            my $seek = process_keys($current_word, $current_orp, $wn);
            if ($seek < 0) {
                my $newpos = $idx + $seek - 1;
                $newpos = 0 if $newpos < 0;
                $idx = $newpos;
                $wordcounter += $seek;
                $wordcounter = 0 if $wordcounter < 0;
                $next_word_time = time();
            }
            $next_input_time += 0.05;
        }

        show_word($current_word, $current_orp);

        my $sleep_time = ($next_word_time < $next_input_time && !$paused)
            ? $next_word_time - time()
            : $next_input_time - time();
        sleep($sleep_time) if $sleep_time > 0;
    }

    teardown_fullscreen() if $fullscreen;
    print_stats();
    sleep(1);
}


package rawinput;

# Ad-hoc interface to interactive terminal input (Term::Screen reads from stdin,
# not /dev/tty, which breaks when stdin is a pipe).

sub new {
    my $class = shift;
    my $self;
    open $self, '/dev/tty';
    bless $self, $class;
    stty('min', '1', '-icanon', '-echo');
    return $self;
}

sub DESTROY {
    stty('cooked', 'echo');
}

sub stty {
    my $self = shift if ref $_[0];
    eval { system('stty', $^O eq 'darwin' ? '-f' : '-F', '/dev/tty', @_); };
}

sub key_pressed {
    my $self = shift;
    my $readfields = '';
    vec($readfields, fileno($self), 1) = 1;
    my $ready = 0;
    eval { $ready = select($readfields, undef, undef, 0); };
    return $ready;
}

sub getch {
    my $self = shift;
    getc($self);
}
